[workspace.package]
version  = "0.2.0"

[workspace]

members = ["member"]
exclude = ["excluded"]

[workspace.dependencies]
member = { path = "member", version = "0.1.0" }
excluded = { path = "excluded" }
