[workspace.package]
version = "0.1.0"

[workspace]

members = ["member"]
exclude = ["excluded"]

[workspace.dependencies]
member = { path = "member" }
excluded = { path = "excluded" }
hex-literal = { version = "0.3.4" }